# Generated by Django 5.1.5 on 2025-01-23 07:15

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', django_cryptography.fields.encrypt(models.EmailField(db_index=True, max_length=100, unique=True))),
                ('password_hash', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True))),
                ('address', django_cryptography.fields.encrypt(models.TextField(blank=True, null=True))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Inactive', 'Inactive')], default='Active', max_length=9)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
