# Generated by Django 5.1.5 on 2025-01-24 06:10

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(db_index=True, max_length=100)),
        ),
    ]
